server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/ordersystem
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

servlet:
  multipart:
    max-file-size: 1000MB
    max-request-size: 1000MB

cloud:
  aws:
    credentials:
      access-key: xxxxxxx
      secret-key: yyyyyyy
    region:
      static: ap-northeast-2
    s3:
      bucket: jiki-bucket

jwt:
  expirationAt: 1000 # 1000분 세팅
  # 인코딩된 문자 32자 이상 필요 (특수문자 X)
  # beyondaccesstokensecretkeybeyondaccesstokensecretkeybeyondaccesstokensecretkey
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 50000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
